# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jin-Doh's Blog
description: "Junior developer, Jin-Doh!"
keywords: "WSL2, Development, 개발, 코딩, 주니어 개발자, git, github, php, nginx, LEMP, 윈도우"
url: https://jin-doh.github.io/
#baseurl: "/end2end"
baseurl: ""

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jin-Doh
  job: Junior Developer
  bio: "Welcome to my small cute development blog"
  thumb: /images/AR(Head).svg
  email: qqaa3030@gmail.com
  url: https://jin-doh.github.io/
  github: https://github.com/Jin-Doh
  #twitter: https://twitter.com/umdevux
  #facebook: https://facebook.com/umdevux
  #linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
